services:
  database:
    image: 'postgres:18.0'
    container_name: 'my_postgres_db'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'demo_db'
    ports:
        - '5434:5432'
    volumes:
        - 'db_data:/var/lib/postgresql'
    networks:
        demo:
  minio:
    image: 'minio/minio:latest'
    container_name: 'my_minio'
    environment:
      MINIO_ROOT_USER: 'admin'
      MINIO_ROOT_PASSWORD: 'admin1234'
      MINIO_NOTIFY_WEBHOOK_ENABLE_DEMO: 'on'
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_DEMO: 'http://localhost:8080/files/upload/webhook'
      MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_DEMO: 'S8h3Pd5sL2r9vV1dZxT3qL9bU6eN8tJ1'
    command: 'server /data --console-address ":9001"'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
      - './init-minio.sh:/docker-entrypoint-init.d/init-minio.sh'
    entrypoint: [ "/bin/sh", "-c", "minio server /data --console-address :9001 & sleep 5 && sh /docker-entrypoint-init.d/init-minio.sh && wait" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      demo:
  redis:
    image: 'redis:8.2.3'
    container_name: 'my_redis'
    environment:
      REDIS_ARGS: '--requirepass admin1234 --user admin on > mypassword ~* allcommands --user default off nopass nocommands'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    networks:
      demo:
networks:
  demo:
    driver: 'bridge'
volumes:
    db_data:
    minio_data:
    redis_data: