spring:
  data:
    redis:
      host: localhost
      port: 6379
      username: admin
      password: admin1234

  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  application:
    name: demo

minio:
    url: http://localhost:9000
    access-key: admin
    secret-key: admin1234
    bucket: demo
    upload-path: upload
    upload-temp-path: upload-temp
    webhook-token: 6jvX8^2uo#^Zc+Ve@1K@Rx6ZBt@9LfxRc8gd#os/wf^=

redis-streams:
  uploads:
    consumer-group: minio_uploads_group
    stream-key: minio_uploads